### ISSUE TITLE
[PE-D] No error message is shown if the data file is corrupted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W10-3/tp#161]
I modified the data file to add a `React.js` under the framework field of a person, and tried opening up the app again. This caused the app to load without any data shown, and no error message was shown either. I think this might be confusing to the user why there's no information shown, and the user might unintentionally overwrite the data file instead of trying to fix it.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: yzhilong/ped#12

**Comment by timothywongej** [comment]
Noted! Thank you for the suggestion. We will keep it in mind for future versions and add it to our User Guide. Currently, the logger displays in the terminal. 

As for the `React.js` bug, it was due to the validation regex of **Framework** which has been resolved! 

Falls outside the allowance for v1.4 changes.
